# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cosc/student/joh29/Desktop/git/cosc363-assignment2-joh29

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cosc/student/joh29/Desktop/git/cosc363-assignment2-joh29

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cosc/student/joh29/Desktop/git/cosc363-assignment2-joh29/CMakeFiles /home/cosc/student/joh29/Desktop/git/cosc363-assignment2-joh29/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cosc/student/joh29/Desktop/git/cosc363-assignment2-joh29/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLProject/OpenGLProject/joh29_raytracer

# Build rule for target.
OpenGLProject/OpenGLProject/joh29_raytracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenGLProject/OpenGLProject/joh29_raytracer
.PHONY : OpenGLProject/OpenGLProject/joh29_raytracer

# fast build rule for target.
OpenGLProject/OpenGLProject/joh29_raytracer/fast:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build
.PHONY : OpenGLProject/OpenGLProject/joh29_raytracer/fast

OpenGLProject/OpenGLProject/Plane.o: OpenGLProject/OpenGLProject/Plane.cpp.o

.PHONY : OpenGLProject/OpenGLProject/Plane.o

# target to build an object file
OpenGLProject/OpenGLProject/Plane.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Plane.cpp.o
.PHONY : OpenGLProject/OpenGLProject/Plane.cpp.o

OpenGLProject/OpenGLProject/Plane.i: OpenGLProject/OpenGLProject/Plane.cpp.i

.PHONY : OpenGLProject/OpenGLProject/Plane.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/Plane.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Plane.cpp.i
.PHONY : OpenGLProject/OpenGLProject/Plane.cpp.i

OpenGLProject/OpenGLProject/Plane.s: OpenGLProject/OpenGLProject/Plane.cpp.s

.PHONY : OpenGLProject/OpenGLProject/Plane.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/Plane.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Plane.cpp.s
.PHONY : OpenGLProject/OpenGLProject/Plane.cpp.s

OpenGLProject/OpenGLProject/Ray.o: OpenGLProject/OpenGLProject/Ray.cpp.o

.PHONY : OpenGLProject/OpenGLProject/Ray.o

# target to build an object file
OpenGLProject/OpenGLProject/Ray.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Ray.cpp.o
.PHONY : OpenGLProject/OpenGLProject/Ray.cpp.o

OpenGLProject/OpenGLProject/Ray.i: OpenGLProject/OpenGLProject/Ray.cpp.i

.PHONY : OpenGLProject/OpenGLProject/Ray.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/Ray.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Ray.cpp.i
.PHONY : OpenGLProject/OpenGLProject/Ray.cpp.i

OpenGLProject/OpenGLProject/Ray.s: OpenGLProject/OpenGLProject/Ray.cpp.s

.PHONY : OpenGLProject/OpenGLProject/Ray.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/Ray.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Ray.cpp.s
.PHONY : OpenGLProject/OpenGLProject/Ray.cpp.s

OpenGLProject/OpenGLProject/RayTracer.o: OpenGLProject/OpenGLProject/RayTracer.cpp.o

.PHONY : OpenGLProject/OpenGLProject/RayTracer.o

# target to build an object file
OpenGLProject/OpenGLProject/RayTracer.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/RayTracer.cpp.o
.PHONY : OpenGLProject/OpenGLProject/RayTracer.cpp.o

OpenGLProject/OpenGLProject/RayTracer.i: OpenGLProject/OpenGLProject/RayTracer.cpp.i

.PHONY : OpenGLProject/OpenGLProject/RayTracer.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/RayTracer.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/RayTracer.cpp.i
.PHONY : OpenGLProject/OpenGLProject/RayTracer.cpp.i

OpenGLProject/OpenGLProject/RayTracer.s: OpenGLProject/OpenGLProject/RayTracer.cpp.s

.PHONY : OpenGLProject/OpenGLProject/RayTracer.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/RayTracer.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/RayTracer.cpp.s
.PHONY : OpenGLProject/OpenGLProject/RayTracer.cpp.s

OpenGLProject/OpenGLProject/Scene.o: OpenGLProject/OpenGLProject/Scene.cpp.o

.PHONY : OpenGLProject/OpenGLProject/Scene.o

# target to build an object file
OpenGLProject/OpenGLProject/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Scene.cpp.o
.PHONY : OpenGLProject/OpenGLProject/Scene.cpp.o

OpenGLProject/OpenGLProject/Scene.i: OpenGLProject/OpenGLProject/Scene.cpp.i

.PHONY : OpenGLProject/OpenGLProject/Scene.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Scene.cpp.i
.PHONY : OpenGLProject/OpenGLProject/Scene.cpp.i

OpenGLProject/OpenGLProject/Scene.s: OpenGLProject/OpenGLProject/Scene.cpp.s

.PHONY : OpenGLProject/OpenGLProject/Scene.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Scene.cpp.s
.PHONY : OpenGLProject/OpenGLProject/Scene.cpp.s

OpenGLProject/OpenGLProject/SceneObject.o: OpenGLProject/OpenGLProject/SceneObject.cpp.o

.PHONY : OpenGLProject/OpenGLProject/SceneObject.o

# target to build an object file
OpenGLProject/OpenGLProject/SceneObject.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/SceneObject.cpp.o
.PHONY : OpenGLProject/OpenGLProject/SceneObject.cpp.o

OpenGLProject/OpenGLProject/SceneObject.i: OpenGLProject/OpenGLProject/SceneObject.cpp.i

.PHONY : OpenGLProject/OpenGLProject/SceneObject.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/SceneObject.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/SceneObject.cpp.i
.PHONY : OpenGLProject/OpenGLProject/SceneObject.cpp.i

OpenGLProject/OpenGLProject/SceneObject.s: OpenGLProject/OpenGLProject/SceneObject.cpp.s

.PHONY : OpenGLProject/OpenGLProject/SceneObject.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/SceneObject.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/SceneObject.cpp.s
.PHONY : OpenGLProject/OpenGLProject/SceneObject.cpp.s

OpenGLProject/OpenGLProject/Sphere.o: OpenGLProject/OpenGLProject/Sphere.cpp.o

.PHONY : OpenGLProject/OpenGLProject/Sphere.o

# target to build an object file
OpenGLProject/OpenGLProject/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Sphere.cpp.o
.PHONY : OpenGLProject/OpenGLProject/Sphere.cpp.o

OpenGLProject/OpenGLProject/Sphere.i: OpenGLProject/OpenGLProject/Sphere.cpp.i

.PHONY : OpenGLProject/OpenGLProject/Sphere.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Sphere.cpp.i
.PHONY : OpenGLProject/OpenGLProject/Sphere.cpp.i

OpenGLProject/OpenGLProject/Sphere.s: OpenGLProject/OpenGLProject/Sphere.cpp.s

.PHONY : OpenGLProject/OpenGLProject/Sphere.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Sphere.cpp.s
.PHONY : OpenGLProject/OpenGLProject/Sphere.cpp.s

OpenGLProject/OpenGLProject/TextureBMP.o: OpenGLProject/OpenGLProject/TextureBMP.cpp.o

.PHONY : OpenGLProject/OpenGLProject/TextureBMP.o

# target to build an object file
OpenGLProject/OpenGLProject/TextureBMP.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/TextureBMP.cpp.o
.PHONY : OpenGLProject/OpenGLProject/TextureBMP.cpp.o

OpenGLProject/OpenGLProject/TextureBMP.i: OpenGLProject/OpenGLProject/TextureBMP.cpp.i

.PHONY : OpenGLProject/OpenGLProject/TextureBMP.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/TextureBMP.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/TextureBMP.cpp.i
.PHONY : OpenGLProject/OpenGLProject/TextureBMP.cpp.i

OpenGLProject/OpenGLProject/TextureBMP.s: OpenGLProject/OpenGLProject/TextureBMP.cpp.s

.PHONY : OpenGLProject/OpenGLProject/TextureBMP.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/TextureBMP.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/TextureBMP.cpp.s
.PHONY : OpenGLProject/OpenGLProject/TextureBMP.cpp.s

OpenGLProject/OpenGLProject/Window.o: OpenGLProject/OpenGLProject/Window.cpp.o

.PHONY : OpenGLProject/OpenGLProject/Window.o

# target to build an object file
OpenGLProject/OpenGLProject/Window.cpp.o:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Window.cpp.o
.PHONY : OpenGLProject/OpenGLProject/Window.cpp.o

OpenGLProject/OpenGLProject/Window.i: OpenGLProject/OpenGLProject/Window.cpp.i

.PHONY : OpenGLProject/OpenGLProject/Window.i

# target to preprocess a source file
OpenGLProject/OpenGLProject/Window.cpp.i:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Window.cpp.i
.PHONY : OpenGLProject/OpenGLProject/Window.cpp.i

OpenGLProject/OpenGLProject/Window.s: OpenGLProject/OpenGLProject/Window.cpp.s

.PHONY : OpenGLProject/OpenGLProject/Window.s

# target to generate assembly for a file
OpenGLProject/OpenGLProject/Window.cpp.s:
	$(MAKE) -f CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/build.make CMakeFiles/OpenGLProject/OpenGLProject/joh29_raytracer.dir/OpenGLProject/OpenGLProject/Window.cpp.s
.PHONY : OpenGLProject/OpenGLProject/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... OpenGLProject/OpenGLProject/joh29_raytracer"
	@echo "... OpenGLProject/OpenGLProject/Plane.o"
	@echo "... OpenGLProject/OpenGLProject/Plane.i"
	@echo "... OpenGLProject/OpenGLProject/Plane.s"
	@echo "... OpenGLProject/OpenGLProject/Ray.o"
	@echo "... OpenGLProject/OpenGLProject/Ray.i"
	@echo "... OpenGLProject/OpenGLProject/Ray.s"
	@echo "... OpenGLProject/OpenGLProject/RayTracer.o"
	@echo "... OpenGLProject/OpenGLProject/RayTracer.i"
	@echo "... OpenGLProject/OpenGLProject/RayTracer.s"
	@echo "... OpenGLProject/OpenGLProject/Scene.o"
	@echo "... OpenGLProject/OpenGLProject/Scene.i"
	@echo "... OpenGLProject/OpenGLProject/Scene.s"
	@echo "... OpenGLProject/OpenGLProject/SceneObject.o"
	@echo "... OpenGLProject/OpenGLProject/SceneObject.i"
	@echo "... OpenGLProject/OpenGLProject/SceneObject.s"
	@echo "... OpenGLProject/OpenGLProject/Sphere.o"
	@echo "... OpenGLProject/OpenGLProject/Sphere.i"
	@echo "... OpenGLProject/OpenGLProject/Sphere.s"
	@echo "... OpenGLProject/OpenGLProject/TextureBMP.o"
	@echo "... OpenGLProject/OpenGLProject/TextureBMP.i"
	@echo "... OpenGLProject/OpenGLProject/TextureBMP.s"
	@echo "... OpenGLProject/OpenGLProject/Window.o"
	@echo "... OpenGLProject/OpenGLProject/Window.i"
	@echo "... OpenGLProject/OpenGLProject/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

